# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  postgres:
    image: postgres:13.10
    networks:
      - backend_db
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: maybeyolo/taski_backend
    networks:
      - backend_db
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: maybeyolo/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: maybeyolo/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80

networks:
  backend_db:
    # Use a custom driver
    driver: custom-driver-1
